index:
    path: /
    controller: App\Controller\IndexController::index

film:
    path: /film/{id}
    controller: App\Controller\FilmController::showFilm

login:
    path: /login
    controller: App\Controller\LoginController::login

category:
    path: /category/{id}
    controller: App\Controller\CategoryController::showFilms

newcategory:
    path: /new/category
    controller: App\Controller\CategoryController::addCategory

categories:
    path: /category
    controller: App\Controller\CategoryController::showCategories


categoriesFiler:
    path: /category/filter/{letter}
    controller: App\Controller\CategoryController::filter

users:
    path: /users/{id}
    controller: App\Controller\UserController::showUserDetails

newUsers:
    path: /new/user
    controller: App\Controller\UserController::addUser
    

    
    

