index:
    path: /
    controller: App\Controller\IndexController::index

mFilm:
    path: /film/{id}
    controller: App\Controller\filmController::showFilm

login:
    path: /login
    controller: App\Controller\LoginController::login

category:
    path: /category/{id}
    controller: App\Controller\CategoryController::showFilms

users:
    path: /user/{id}
    controller: App\Controller\UserController::showUserDetails

